.travis.yml, .travis/install-linux-deps.sh, .travis/install-osx-deps.sh, .travis/install-petsc.sh, README.md, demo/makefile
Support for [Travis-CI](https://travis-ci.org/TDycores-Project/TDycore/builds) and [CodeCov](https://codecov.io/gh/TDycores-Project/TDycore) is added using an approach that is
similar to the one used in [PFLOTRAN](https://bitbucket.org/pflotran/pflotran).
=> Adds support for Travis-CI and CodeCov

.travis.yml, demo/makefile, makefile
- Update the Travis-CI yml script to include coverage of the TDycore lib
- Also, updates the makefile for the library and demo code to include code coverage
flags.
=> Fixes code coverage via CodeCov

.travis/install-petsc.sh
PETSc version for Travis-CI is updated from v3.10.4 to v3.11.1
=> Updates the PETSc version for Travis-CI

demo/steady/steady.c
Corrects the smooth deformation of the mesh for the  2D problem.
Reported by @rezgarshakeri
Fixes #41
=> Fixes the 2D problem from Wheeler et al. (2012)

README.md
Added some basic info and installation-related information to the README file.
=> Added some stuff to the README.

include/tdytimers.h, src/mpfao/3D/tdympfao3D_core.c, src/mpfao/3D/tdympfao3D_snes.c, src/mpfao/3D/tdympfao3D_steady.c, src/mpfao/3D/tdympfao3D_th_ts.c, src/mpfao/3D/tdympfao3D_ts.c, src/mpfao/3D/tdympfao3D_ts_dae.c, src/mpfao/3D/tdympfao3D_ts_transientvar.c, src/mpfao/tdympfao.c, src/tdycore.c
This is the first in a series of timer instrumentation PRs.
In order to make things less disruptive, I'm going to be adding a bunch of timers in short spurts to keep from interfering too much with everyone's work. Most of them aren't going to be properly categorized in stages till a later PR, but that's my problem till everyone starts doing performance profiling.
=> MPFA-O timers: part 1

.travis/install-petsc.sh, demo/richards/richards_driver.c, include/tdyio.h, src/tdydm.c, src/tdyio.c, src/tdyti.c
This is the rebased and squashed version of Rosie's updates
=> refactored TDyIO to include exodus

demo/richards/richards_driver.c
The code modification disables the output of Exodus II file for
a parallel run.
Fixes #95
=> Disable the I/O for parallel run

src/mpfao/3D/tdympfao3D_ts.c
Now we set all row values simultaneously. Regression tests pass.
I haven't profiled the performance to compare, but this should be
a bit faster.
I also moved variable declarations in the relevant function within
the scope of their usage. This is a modern way of declaring variables
that aids learning and debugging, because it makes clear how variables
are used instead of piling them at the top of a function. Unfortunately,
Fortran doesn't support it, so it might look a bit weird for some.
=> Changed invocation of MatSetValuesLocal in 3D MPFAO TS.

doc/sphinx/source/styleguide.rst
This is all negotiable. It's just a starting point, not intended to offend anyone. :-) Please add whoever you think might care about this stuff to the list of reviewers.
Closes #118
=> Rough draft of a style guide. Let the holy wars begin!

doc/sphinx/source/styleguide.rst, src/mesh/tdyregion.c
To get us started documenting our API, I added what I recommend we use in Doxygen's markup.
On an almost-unrelated issue: I confess I'm still a bit confused about how the `TDyRegion` type is used in practice, and the function that adds cells to it could be improved. But it's probably not a high priority. @bishtgautam , let me know if you are bored and want to discuss it.
Closes #128
=> Added some Doxygen markup examples to the style guide and to the TDyRegion type.

doc/sphinx/source/conf.py
=> Added a missing bibtex config parameter.

README.md
=> Fixed build status badge.

Doxyfile
Removes libCEED directories and adds TDycore directories.
=> Fixes the input directories for Doxygen

include/private/tdymeshimpl.h, include/tdycore.h, src/mesh/tdycoremesh.c, src/mesh/tdymesh.c
See #147 for details on this one. We don't have unit tests yet--a candidate mechanism for that is in PR #146.
There are two things remaining for #147:
1. Self-contained mesh constructor(s) for creating standalone mesh objects.
2. Unit tests that manipulate these objects
=> Added interface functions for efficiently and clearly accessing mesh entities.

src/mpfao/3D/tdympfao3D_utils.c, src/tdyio.c
Minor code changes to fix few warnings.
=> Removes few warnings

src/tdyio.c
Updates TDycore so it is compatible with recent changes in PETSc. 
The merge-request that includes changes to Exodus in PETSC 
is https://gitlab.com/petsc/petsc/-/merge_requests/3836/diffs.
=> updated exodus commands with new petsc functions

include/private/tdyioimpl.h, src/tdyio.c
Removed calls to PETSc's internal functions
=> removed internal function for exodus output

demo/SPE10/steady.c, demo/mpfao/mpfao.c, demo/qa_test/qa_test.c, demo/steady/steady.c, demo/steadyblock/steadyblock.c, demo/transient/transient.c, demo/transient/transient_mpfao.c, demo/transient/transient_th_mpfao.c, include/private/tdymaterialpropertiesimpl.h, src/tdymaterialproperties.c
Changes variable type as reported by @rtmills in #170
=> Replaces variables defined as double with PetscReal

src/mesh/tdycoremesh.c
The updated code now puts the cells with minimum numbers of
neighbors at the start and end of array containing the cells
ids that needed to be rearranged. The rearranged array is
next sorted to ensure cell `i` and `i+1` are neighbors.
=> Fixes the logic to arrange cells in circular order

src/mesh/tdycoremesh.c, src/mesh/tdycoremeshutils.c, src/tdyio.c
Just a minor commit that gets rid of a few compiler warnings to reduce noise.
=> Fixes a few compiler warnings (and some whitespace).

include/private/tdydiscretization.h, src/mesh/tdycoremesh.c, src/mesh/tdycoremeshutils.c, src/mpfao/2D/tdympfao2D.c, src/mpfao/3D/tdympfao3D_snes.c, src/mpfao/3D/tdympfao3D_th_ts.c, src/mpfao/3D/tdympfao3D_ts.c, src/mpfao/3D/tdympfao3D_ts_dae.c, src/mpfao/3D/tdympfao3D_ts_transientvar.c, src/mpfao/3D/tdympfao3D_utils.c, src/mpfao/tdympfao.c, src/tdycore.c, src/tdydiscretization.c, src/tdyio.c, src/tdyregression.c, src/tdywy.c
TDy wrappers for the following DM functions are added
- Creation of vectors
- Creation of matrix
- Communication of vectors
=> Adds new wrapper functions for DM functions

demo/steadyf90/steadyf90.F90, demo/transient/transient_snes_mpfaof90.F90
- Changes `CHKERRQ` to `CHKERRA`
- Corrects the call to report an error
=> Minor fixes for F90 demos to compile on Cori

src/tdyio.c
Adds the missing call to create a PETSc vector.
=> Adds creation of a vector

doc/sphinx/source/development.rst
This PR just adds a section describing the new memory allocation/deallocation functions. No code changes.
=> Updated documentation with new memory allocation interface.
