TDycores-Project/TDycore

- .astylerc
- demo/steady.c
- demo/transient.c
- include/tdycore.h
- makefile
- src/tdybdm.c
- src/tdycore.c
- src/tdydebug.c
- src/tdypermeability.c
- src/tdyporosity.c
- src/tdysaturation.c
- src/tdytpf.c
- src/tdywy.c
Borrows the .astyle format that is used by the https://github.com/CEED/libCEED.
`make style` will perform the style check. The style of all files (*.c and *.h)
is updated.
> Adds support for style check via astyle

- include/private/tdycoreimpl.h
- src/tdybdm.c
- src/tdycore.c
- src/tdywy.c
This restores linear complexity to WY assembly and speeds it up by 100x. 
A function was implemented to check the number of vertices per cell and face 
and then called this inside a loop over cells. The fix is to store the integer and
read it when needed.
> Fixes to slow assembly for WY and BDM.

- demo/steady/makefile
- src/tdycore.c
This is a simple patch enforces default quadrature for BDM spaces to be full.
> Sets default quadrature for BDM spaces to be full

- src/tdycore.c
Few error checks are added to catch invalid specification via `-tdy_method`.
> Adds few missing error checks

- demo/mpfao/makefile
- demo/mpfao/mpfao.cfg
- include/private/tdycoreimpl.h
- include/private/tdymeshimpl.h
- src/tdycore.c
- src/tdycoremesh.c
- src/tdympfao.c
By adding `-tdy_output_mesh` to command line, the mesh attributes and connectivity
information is outputted. Additionally, a regression test is updated to test the new option.
> Adds an option to output mesh connectivity

- demo/SPE10/steady.c
- include/tdycore.h
- src/tdycore.c
- src/tdypermeability.c
- src/tdywy.c
Removes entries in the system matrix when a diagonal permeability is used on a regular grid. 
This would result in fewer non-zero entries and reduce the cost of MatVec products. 
Additionally, adds some accessors for TDy data such as the dimension such that we need
not include private headers in application code.
> Modifications to improve SPE performance

- demo/SPE10/steady.c
- demo/mpfao/mpfao.c
- demo/steady/steady.c
- demo/transient/transient.c
Moved DMSetFromOptions() calls to be after the calls to DMPlexDistribute(). We destroy the original 'dm' after the latter, so we were losing the DM-related options when we were doing things in the original order.
> Moved DMSetFromOptions() calls to occur after DMPlexDistribute().

- regression_tests/regression_tests.py
Nonzero exit code generates error output with Open MPI, which we don't
want in case of successful completion.
Glenn:
I don’t recall the original logic back in 2012. But we key off it
now to differentiate between user error and a crash.  Just set it to
zero
> regression_tests: use exit code 0 for success [fix #34]

- demo/transient/transient_mpfao.c
- demo/transient/transient_th_mpfao.c
- src/mpfao/3D/tdympfao3D_th_ts.c
- src/mpfao/3D/tdympfao3D_utils.c
- src/tdycore.c
Changes `sizeof(Vec)` to `sizeof(PetscReal)`
> Corrects the data type while allocating memory

- include/private/tdympfao3Dtsimpl.h
- src/mpfao/3D/tdympfao3D_snes.c
- src/mpfao/3D/tdympfao3D_ts.c
- src/mpfao/3D/tdympfao3D_ts_dae.c
- src/mpfao/3D/tdympfao3D_ts_transientvar.c
- src/mpfao/3D/tdympfao3D_utils.c
- src/tdycore.c
Three IFunctions for residual computation that were previously separated by 
type of vertex (e.g. internal vertex, boundary vertex that is shared by an internal 
vertex or boundary vertex that is not shared by an internal vertex) are replaced by
a single function.
The two IJacobian functions for internal and boundary vertex shared by an internal
vertex are replaced by a single function.
The IJacobina function for boundary vertex not shared by an internal vertex is commented
out as it is not called from any other function.
> Refactors residual and jacobian computation for RICHARDS + MPFA-O

- GNUmakefile
- demo/SPE10/makefile
- demo/mpfao/makefile
- demo/steady/makefile
- demo/steadyblock/makefile
- demo/steadyf90/makefile
- demo/steadyf90/steadyf90.F90
- demo/transient/makefile
- demo/transient/transient_mpfaof90.F90
- demo/transient/transient_snes_mpfaof90.F90
- gmakefile
- makefile
- regression_tests/Makefile
- regression_tests/regression_tests.py
You can now run
make -j4 test
to run the full test suite in parallel, rebuilding library and demos as needed. Or
make -j4 test-steady
to run any single test, also rebuilding (in parallel) anything that's needed. Use `make print-ALLTESTS` to list all options.
We could remove pretty much all the other makefiles, but I've left them intact for now. We could also place the compiled demos into `PETSC_ARCH`, which I've also skipped to avoid disrupting a workflow that moves into the demo directory.
> Enable testing from top-level makefile

- demo/SPE10/steady.c
- demo/mpfao/mpfao.c
- demo/steady/steady.c
- demo/steadyblock/steadyblock.c
- demo/steadyf90/steadyf90.F90
- demo/transient/transient.c
- demo/transient/transient_mpfao.c
- demo/transient/transient_mpfaof90.F90
- demo/transient/transient_snes_mpfaof90.F90
- demo/transient/transient_th_mpfao.c
- include/private/tdydmimpl.h
- include/tdycore.h
- include/tdydm.h
- src/interface/ftn/tdycoref.c
- src/interface/ftn/tdydmf.c
- src/tdycore.c
- src/tdydm.c
The TDy library can create a default DM if none is specified.
One can continue to create TDy by explicitly specifying a DM.
> Refactors creation of DM

- src/mesh/tdycoremesh.c
- src/mpfao/tdympfao.c
- src/tdydm.c
- The code that determines cell-ids above/below now skips non-local vertices
- Additionally, `TDyDistributeDM` is modified to use `DMSetUseNatural` before 
partitioning the domain. This change allows the mapping of natural cells to
local ids.
Fixes #93
> Fixes parallel MPFA-O run

- src/mpfao/3D/tdympfao3D_snes.c
- src/mpfao/3D/tdympfao3D_th_ts.c
- src/mpfao/3D/tdympfao3D_ts.c
When computing jacobian, values are set for the preconditioner matrix `Pmat` instead
of `Amat`.  This modification allows the use of numerical jacobian from PETSc via `-snes_mf_operator`
instead of analytical jacobian. 
The `Amat` and `Pmat` for PETSc SNES are described [here](https://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/SNES/SNESSetJacobian.html).
Fixes #90
> Corrects the matrix to save jacobian entries

- demo/transient/transient_snes_mpfaof90.cfg
- regression_tests/makefile
- src/tdyio.c
Added preprocessing to avoid ExodusII code when PETSc is not configured with it.
added condition in regression test makefile to skip ExodusII tests
Fixes #125
> Allows code to compile without ExodusII

- .github/workflows/auto_publish_docs.yml
- doc/sphinx/source/conf.py
- doc/sphinx/source/development.rst
This adds a GitHub Action that builds the documentation for TDycore and sticks it into the `docs/` directory of the `github_pages` branch. We've pointed GitHub Pages at this location, and you can find the generated site here:
https://tdycores-project.github.io/TDycore/
Documentation is published whenever a PR is merged into the `master` branch.
Whenever it makes sense, we can point `tdycore.org` to this location. Thanks, Jed, for pointing out the GitHub Action that makes this easy.
Closes #129
> Documentation is now published to GitHub Pages

- src/mesh/tdycoremesh.c
This is just a source cleanup of tdycoremesh.c. I removed a lot of the Fortran-like "walls of variables" at the beginnings of functions, moving them to where these variables are used. As explained in our style guide, this reduces the number of places that they can (a) contain irrelevant data and (b) cause problems.
Pertains to #135
> Cleaning up tdycoremesh.c to limit "surface area" of variables.

- .github/workflows/auto_pr_test.yml
- tools/Dockerfile.petsc
- tools/build-petsc-docker-image.sh
This PR intends to speed up our builds by using a Docker image that is tailor-made for the project. The tools used to generate this docker image live in the `tools/` directory.
We were discussing a workflow that allowed us to automatically generate a Docker image when requested (somehow), but this gets us most of the way. We can further automate it if the tools here aren't convenient enough.
For now I've created a Docker image and stuck it in my own DockerHub account (`coherellc`). It's very easy to change where we store this, and I think we can also use GitHub's Docker registry, though it's very new and still in beta.
Closes #142
> Adding tools for creating and pushing Docker images

- .gitignore
- demo/.gitignore
- include/tdycore.h
- src/mesh/tdycoremesh.c
- src/mesh/tdycoremeshutils.c
- src/mesh/tdymesh.c
- src/mpfao/2D/tdympfao2D.c
- src/mpfao/3D/tdympfao3D_core.c
- src/mpfao/3D/tdympfao3D_steady.c
- src/mpfao/3D/tdympfao3D_th_ts.c
- src/mpfao/3D/tdympfao3D_ts.c
- src/mpfao/3D/tdympfao3D_utils.c
- src/tdyio.c
The code changes include:
1. Use of refactored mesh functions to access various member variables of TDy mesh elements to avoid using `*Offset*`. e.g.
Old approach
```
PetscInt sOffsetFace = subcells->face_offset[subcell_id];
for (iface=0;iface<subcells->num_faces[subcell_id];iface++) {
PetscInt face_id = subcells->face_ids[sOffsetFace + iface];
...
}
```
New approach:
```
PetscInt *face_ids, num_faces;
ierr = TDyMeshGetSubcellFaces(mesh, subcell_id, &face_ids, &num_faces); CHKERRQ(ierr);
for (iface=0;iface<subcells->num_faces[subcell_id];iface++) {
PetscInt face_id = face_ids[iface];
}
```
2. Conversion of `TDySubcell` and `TDyVector` data to a compressed format.
Note: 
- There is no need to compress `TDyFace` as it is already in compressed format.
- `TDyCell` is not converted in the …
> Updates the code to use refactored mesh functions

- include/private/tdympfao3Dcoreimpl.h
- src/mesh/tdycoremesh.c
- src/mpfao/3D/tdympfao3D_core.c
- src/mpfao/tdympfao.c
- Corrects the offset value when converting mesh elements to a compressed format
- Cleans up code by removing unused variables and splitting Gmatrix computation
> Fixes TPF for parallel runs

- .github/workflows/auto_pr_test.yml
- tools/Dockerfile.petsc
They're also displayed at the beginning of TDycore's build process in the PR auto-test workflow.
Sorry for the noise on this one.
> PETSc hashes are now correctly handled in creation of Docker images.

- .github/workflows/auto_pr_test.yml
- gmakefile
- src/tests/run_unit_tests.sh
- src/tests/tdycore_tests.h
- src/tests/test_tdyinit.c
- tools/Dockerfile.petsc
Here's another illustration of how we might use CMocka to write unit tests. This PR uses `pkg-config` to determine whether CMocka is available, and then provides targets for running unit tests. These targets aren't finished yet--they just run all the tests in one process. I wanted to focus for now on how one might poll a test executable for the number of tests and then run them one at a time.
To see all this, try the following:
```
make unit-tests
./src/tests/test_tdyinit count
./src/tests/test_tdyinit 0
./src/tests/test_tdyinit 1
./src/tests/test_tdyinit 2
./src/tests/test_tdyinit 3
```
One drawback of this approach is that command line arguments are not available to unit tests--they are interpreted as a user "talking to" the test harness. Arguably, this isn't a drawback, since …
> Improved CMocka demo: pkg-config support, isolated processes

- gmakefile
- src/tests/test_mesh_labels.c
This PR piggybacks on #146, adding a set of unit tests:
1. Generate a box mesh
2. Read a box mesh
3. Mark boundary faces in the box mesh and write it out
4. Read the labeled box mesh and make sure the boundary faces match a newly created set
I used the HDF5 viewer to read and write the meshes. The Exodus one doesn't seem to be working properly just yet (I get a segfault when trying to write out the original mesh using the Exodus viewer).
Closes #157
> Added a unit test for generating a boxmesh and marking boundary faces.

- src/interface/ftn/tdycoref.c
Changes the capitalized function name to be lowercase. Also, corrects the function
definitions.
> Fixes FORTRAN wrapper names

- doc/sphinx/source/conf.py
Our most recent attempt at auto-publishing our documentation site failed with this error:
```
...
Running Sphinx v4.0.1
Extension error:
Could not import extension sphinxcontrib.mermaid (exception: cannot import name 'ENOENT' from 'sphinx.util.osutil' (/usr/local/lib/python3.8/site-packages/sphinx/util/osutil.py))
make: *** [Makefile:19: html] Error 2
...
[sphinx-action] Starting sphinx-action build.
Running: pip install -r requirements.txt
====================================
Building docs in doc/sphinx
====================================
[sphinx-action] Running: ['make', 'html', '-e']
[sphinx-action] Build failed with 0 warnings
Traceback (most recent call last):
File "/entrypoint.py", line 22, in <module>
action.build_all_docs(github_env, [os.environ.get("INPUT_DOCS-FOLDER")])
File …
```
> Disabling Sphinx mermaid extension, which breaks with Sphinx 4.0+.

- gmakefile
- src/tests/run_unit_tests.sh
- src/tests/tdycore_tests.h
- src/tests/test_mesh_labels.c
- src/tests/test_tdyinit.c
Now we support an initialization function which receives `argc` and `argv` with any test index argument stripped out. You can use this to stash `argc` and `argv`, initialize PETSc, etc.
Also, the `run-tests` target prints out a command for each failed test that allows a user to run that test.
(Also fixed a minor glitch in the mesh labels unit test.)
Closes #176
> Added requested features to CMocka-based unit testing approach.

- gmakefile
- src/tests/run_unit_tests.sh
- src/tests/test_mesh_labels.c
These commits allow failed unit tests to report failures accurately via `make`, which means they'll register as test failures in our autotesting environment.
> Unit tests now report error code failures to make

- src/tdycore.c
Correctly registers TDy` when `TDyCreate()` is called without first calling `TDyInit()`.
> Fixes the registry of TDy

- demo/SPE10/steady.c
- demo/mpfao/mpfao.c
- demo/qa_test/qa_test.c
- demo/steady/steady.c
- demo/steadyblock/steadyblock.c
- demo/steadyf90/steadyf90.F90
- demo/transient/transient.c
- demo/transient/transient_mpfao.c
- demo/transient/transient_mpfaof90.F90
- demo/transient/transient_snes_mpfaof90.F90
- demo/transient/transient_th_mpfao.c
- include/private/tdycoreimpl.h
- include/tdycore.h
- src/interface/ftn/tdycoref.c
- src/mpfao/2D/tdympfao2D.c
- src/mpfao/3D/tdympfao3D_steady.c
- src/mpfao/3D/tdympfao3D_utils.c
- src/mpfao/tdympfao.c
- src/tdybdm.c
- src/tdyconditions.c
- src/tdytpf.c
- src/tdywy.c
* TDySetDirichletValueFunction -> TDySetBoundaryPressureFn
* TDySetTemperatureDirichletValueFunction -> TDySetBoundaryTemperatureFn
* TDySetDirichletFluxFunction -> TDySetBoundaryVelocityFn
Boundary conditions are tricky enough! It's important for us to be precise
about our language. C and Fortran interfaces have been updated, and all the
demos use the new functions.
FYI @ghammond86 @nocollier
> Renamed boundary-condition-related functions to better describe their purposes

- .github/workflows/auto_pr_test.yml
- README.md
- include/tdytimers.h
- tools/build-petsc-docker-image.sh
To clarify our dependencies, we note the tested PETSc revision in our README, and refer to the appropriate Docker image tag in our workflow files. In particular, we no longer use the `latest` tag, which is uninformative.
The only code change needed to adopt this new rev is the location of the `khash` header files.
In support of #188
> Tracking the latest PETSc revision.

- include/tdycore.h
- src/mesh/tdycoremesh.c
- src/tdycore.c
- src/tdyth.c
- src/tdytpf.c
As discussed in #187, this PR introduces the use of `DMPlexMarkBoundaryFaces` to produce a `DMLabel` named `"boundary"` that we can use to enforce boundary conditions. I'm trying to be careful about how we approach this, because our demos are all pretty historical-looking. So this is just another in a series of PRs to improve the organization of the TDycore library.
Additional items:
* If given `-tdy_init_file`,`TDySetFromOptions` allocates storage for the solution vector and friends with `TDyCreateVectors` and initializes things accordingly. I tried to initialize from a random field, too, but TH does this differently, so this must be done elsewhere for now.
* `TDyCreateVectors` and `TDyCreateJacobian` are documented and can be safely called multiple times (with no effect after the first …
> We now construct a DMLabel for boundary faces.

- include/private/tdymeshimpl.h
- include/private/tdymeshutilsimpl.h
- src/mpfao/tdycoremesh.c
- src/mpfao/tdycoremeshutils.c
- src/mpfao/tdympfao.c
- src/mpfao/tdympfao_utils.c
- src/tdycore.c
- src/tdyutils.c
Removes 2D MPFA-O code and renames functions by deleting the `3DMesh` suffix.
Fixes #200
> Removes 2D MPFA-O

- demo/SPE10/steady.c
- demo/steady/steady.c
- demo/transient/transient.c
- demo/transient/transient_mpfaof90.F90
- demo/transient/transient_snes_mpfaof90.F90
- include/private/tdycoreimpl.h
- include/tdycore.h
- src/f90-mod/tdycoremod.F90
- src/interface/ftn/tdycoref.c
- src/tdycore.c
- src/tdydriver.c
This small PR lays part of the foundation for a move to a more solver-based interface. Our objective here, in the spirit of #197, is to move from our current approach of determining the behavior of the dycore (`if` tests in several functions scattered throughout the library, to match the dycore against its type of discretization, etc) to a new approach based on function pointers. The closest handy analogy for most is C++'s implementation of polymorphism using virtual tables. But PETSc itself uses this approach heavily.
In `include/tdycore.h`, line 162, you can see that I've written that certain functions using the old approach will likely be replaced by a smaller set of new polymorphic functions. Specifically, we are adding two new functions:
* `TDySetSNES(TDy dycore, SNES solver)` - …
> A starting point for a polymorphic solver-based TDycore interface.

- include/private/tdyregressionimpl.h
- src/materials/tdymaterialproperties.c
- src/mpfao/tdymesh.c
- src/mpfao/tdympfao.c
- src/mpfao/tdympfao_th_ts.c
- src/tdyconditions.c
- src/tdycore.c
- src/tdyregression.c
I ran Valgrind on the dycore and saw quite a large number of reported leaks. Some leaks come from before our big refactor, and some were introduced by it!
This PR fixes all of the leaks except for one, which is related to the dycore's primary DM. I'm not sure what's going on with it at the moment, but I'd rather get these other fixes in now.
We can probably continue to improve our organization (and slim the FV mesh down a bit--it's got a lot of things at the moment), but this at least gives us a cleaner report from Valgrind.
> Plugged a bunch of memory leaks.

- .github/workflows/auto_pr_test.yml
- README.md
- demo/transient/fv_tpff90.F90
- demo/transient/transient.cfg
- demo/transient/transient_snes_mpfaof90.F90
- demo/transient/transient_snes_mpfaof90.cfg
- include/tdytimers.h
- makefile
- src/tdycore.c
- src/tdyio.c
- tools/Dockerfile.petsc
We recently observed a serious drop in code coverage. This PR seeks to restore code coverage testing in some demos that are missing it, which requires us to adopt new compilers to avoid a known internal compiler error (see comments). Updating compilers means updating our Docker image, and while we're at it, we're also moving to the latest release of PETSc, which contains enhancements to DMPlex.
> Re-establishing code coverage, updating Docker image and PETSc version

- demo/makefile
- demo/salinity/makefile
- demo/salinity/salinity.c
- include/private/tdyconditionsimpl.h
- include/private/tdycoreimpl.h
- include/private/tdyeosimpl.h
- include/private/tdymaterialpropertiesimpl.h
- include/private/tdympfaoimpl.h
- include/private/tdympfaosalinitytsimpl.h
- include/private/tdyoptions.h
- include/private/tdysalinityimpl.h
- include/tdycore.h
- src/fv/fvtpf/tdyfvtpf.c
- src/fv/mpfao/tdympfao.c
- src/fv/mpfao/tdympfao_salinity_ts.c
- src/fv/mpfao/tdympfao_snes_salinity.c
- src/fv/mpfao/tdympfao_th_ts.c
- src/fv/mpfao/tdympfao_utils.c
- src/materials/tdyeos.c
- src/materials/tdymaterialproperties.c
- src/tdyconditions.c
- src/tdycore.c
- src/tdydriver.c
- src/tdysalinity.c
- src/tdyti.c
Hi everyone,
@leorosie and I were working on a lot of things at the same time, so our paths diverged. This PR is a reimagining of PR #239 in the new code structure in which material models, characteristic curves, etc are factored out, and our new "polymorphic" model is in place, with vectorized functions and all that wacky stuff.
I've revised each of Rosie's commits and stuck both of our names on them using a convention suggested by @jedbrown (thanks!). Hopefully the code is similar enough for us to evaluate it alongside PR #239 . I took the liberty of changing the names of a few things ("concentration" to "salinity" to be more specific, and "PorDiff" to "SalineDiffusivity", etc), but these are just suggestions.
It looks like there may be some test failures in the transient MPFAO F90 …
> Commit-by-commit port of Rosie's salinity PR to new code structure

- doc/sphinx/requirements.txt
This PR bumps the version of Markdown to fix a doc build warning, and eliminates the markdown-tables extension, which has rotted and broken our build.
> The markdown-tables extension broke our doc build. Are we even using it?

- doc/sphinx/source/conf.py
The last PR failed to build docs because I didn't remove a reference to the extension we deleted. I am resisting getting a PhD in Sphinx (not a fan).
> Sphinx fix, attempt #2

- demo/SPE10/steady.c
- demo/qa_test/qa_test.c
- demo/richards/richards_driver.c
- demo/salinity/salinity.c
- demo/steady/steady.c
- demo/th/th_driver.c
- demo/transient/transient.c
- src/fe/tdybdm.c
- src/fe/tdywy.c
- src/fv/fvtpf/tdyfvtpf.c
- src/fv/mpfao/tdympfao.c
- src/materials/tdycharacteristiccurves.c
- src/tdycore.c
- src/tdyio.c
- src/tdyregression.c
- src/tdyti.c
We could consider adopting `PetscCall` notation and clang-format if others like it, but this gets things compiling (and fixes a couple format strings).
> Update PetscOptionsBegin/End for petsc-3.18/main
